In [12]:
%config SqlMagic.displaylimit = None
%load_ext sql
%load_ext autoreload
%autoreload 2

displaylimit: Value None will be treated as 0 (no limit)

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

# Materialized Views (precompute expensive reads)
**Where it helps most**
- Aggregations over metrics
- Activity feeds (posts + comments)
- User analytics

## metrics aggregation
Instead of scanning metrics every time:

In [4]:
%%sql
CREATE MATERIALIZED VIEW mv_metrics_daily AS
SELECT 
    metric_name,
    date_trunc('day', recorded_at) AS day,
    avg(value) AS avg_value,
    max(value) AS max_value,
    min(value) AS min_value,
    count(*) AS total_records
FROM metrics
GROUP BY metric_name, day;

1830 rows affected.

++
||
++
++

In [5]:
%%sql
CREATE INDEX idx_mv_metrics_daily 
ON mv_metrics_daily(metric_name, day);

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

++
||
++
++

In [6]:
%%sql
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_metrics_daily;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

RuntimeError: (psycopg2.errors.ObjectNotInPrerequisiteState) cannot refresh materialized view "public.mv_metrics_daily" concurrently
HINT:  Create a unique index with no WHERE clause on one or more columns of the materialized view.

[SQL: REFRESH MATERIALIZED VIEW CONCURRENTLY mv_metrics_daily;]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [10]:
from database_as_crime_scene.jupyter.mermaid import get_mermaid_by_table_name, draw
import os

database_url = os.getenv('DATABASE_URL', 'localhost:5432')

er = get_mermaid_by_table_name(database_url, 'public', 'mv_metrics_daily')

draw(er)

In [18]:
from database_as_crime_scene.jupyter.mermaid import get_mermaid_by_view_name, draw
import os

database_url = os.getenv('DATABASE_URL', 'localhost:5432')

er = get_mermaid_by_view_name(database_url, 'public', 'mv_metrics_daily')

draw(er)

ImportError: cannot import name 'get_mermaid_by_view_name' from 'database_as_crime_scene.jupyter.mermaid' (/app/src/database_as_crime_scene/jupyter/mermaid.py)

In [19]:
from database_as_crime_scene.db.connection import get_query

get_query("SELECT * FROM public.mv_metrics_daily")

,metric_name,day,avg_value,max_value,min_value,total_records
0,cpu_usage,2025-04-10,49.980991,99.97,0.19,2663
1,cpu_usage,2025-04-11,49.958589,99.98,0.01,5302
2,cpu_usage,2025-04-12,50.119725,99.99,0.01,5461
3,cpu_usage,2025-04-13,49.635211,99.98,0.01,5450
4,cpu_usage,2025-04-14,50.032590,99.98,0.01,5606
...,...,...,...,...,...,...
1825,network_latency,2026-04-06,49.594554,100.00,0.00,5419
1826,network_latency,2026-04-07,49.549996,100.00,0.01,5461
1827,network_latency,2026-04-08,49.800885,99.99,0.03,5513
1828,network_latency,2026-04-09,49.577849,99.99,0.01,5420
1829,network_latency,2026-04-10,49.988053,99.93,0.00,2727

##user activity feed

In [15]:
%%sql
CREATE MATERIALIZED VIEW mv_user_activity AS
SELECT 
    u.id AS user_id,
    count(p.id) AS total_posts,
    count(c.id) AS total_comments
FROM users_profile u
LEFT JOIN posts p ON p.fk_user_id = u.id
LEFT JOIN comments c ON c.fk_user_id = u.id
GROUP BY u.id;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

100 rows affected.

++
||
++
++

In [16]:
from database_as_crime_scene.jupyter.mermaid import get_mermaid_by_table_name, draw
import os

database_url = os.getenv('DATABASE_URL', 'localhost:5432')

er = get_mermaid_by_table_name(database_url, 'public', 'mv_user_activity')

draw(er)

In [17]:
from database_as_crime_scene.db.connection import get_query

get_query("SELECT * FROM public.mv_user_activity")

    user_id  total_posts  total_comments
0        55          530             530
1        27          500             500
2        23          490             490
3        56          620             620
4        91          610             610
..      ...          ...             ...
95        1          640             640
96       76          470             470
97        5          480             480
98       18          510             510
99       64          450             450

[100 rows x 3 columns]