# Initial Steps

In [1]:
%load_ext sql
%load_ext autoreload
%load_ext rich

Tip: You may define configurations in /app/pyproject.toml or /root/.jupysql/config.

Did not find user configurations in /app/pyproject.toml.

## imports
> for more details go Library Notebook

In [10]:
from rich import inspect
from rich.pretty import pprint

In [6]:
from database_as_crime_scene.db.connection import get_database_url
conn_string=get_database_url()
print(conn_string)

postgresql://postgres:postgres@postgres:5432/mydb

In [4]:
%sql postgresql://postgres:postgres@postgres:5432/mydb

Connecting and switching to connection 'postgresql://postgres:***@postgres:5432/mydb'

In [5]:
%%sql
SELECT
  1 + 1

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

1 rows affected.

+----------+
| ?column? |
+----------+
|    2     |
+----------+

In [6]:
%%sql
select schemaname as table_schema,
       relname as table_name,
       pg_size_pretty(pg_relation_size(relid)) as table_size
from pg_catalog.pg_statio_user_tables 
where schemaname = 'public'
order by pg_relation_size(relid) desc;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

4 rows affected.

+--------------+---------------+------------+
| table_schema |   table_name  | table_size |
+--------------+---------------+------------+
|    public    |    comments   |  4832 MB   |
|    public    |     posts     |   880 MB   |
|    public    | users_profile |   80 MB    |
|    public    |    friends    |   50 MB    |
+--------------+---------------+------------+

In [5]:
%%sql
SELECT pg_size_pretty(pg_table_size('comments')) AS table_size,
    pg_size_pretty(pg_indexes_size('comments')) AS indexes_size, 
    pg_size_pretty(pg_total_relation_size('comments')) AS total_size;

1 rows affected.

+------------+--------------+------------+
| table_size | indexes_size | total_size |
+------------+--------------+------------+
|  4834 MB   |   2329 MB    |  7163 MB   |
+------------+--------------+------------+

# Discovery

In [6]:
%%sql
SELECT
    table_name,
    pg_size_pretty(pg_table_size(format('%I.%I', table_schema, table_name))) AS table_size,
    pg_size_pretty(pg_indexes_size(format('%I.%I', table_schema, table_name))) AS indexes_size,
    pg_size_pretty(pg_total_relation_size(format('%I.%I', table_schema, table_name))) AS total_size
FROM
    information_schema.tables
WHERE
    table_schema NOT IN ('pg_catalog', 'information_schema')
    AND table_type = 'BASE TABLE'
ORDER BY
    pg_total_relation_size(format('%I.%I', table_schema, table_name)) DESC;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

4 rows affected.

+---------------+------------+--------------+------------+
|   table_name  | table_size | indexes_size | total_size |
+---------------+------------+--------------+------------+
|    comments   |  4834 MB   |   2329 MB    |  7163 MB   |
|     posts     |   881 MB   |    370 MB    |  1251 MB   |
| users_profile |   81 MB    |    128 MB    |   209 MB   |
|    friends    |   50 MB    |    58 MB     |   108 MB   |
+---------------+------------+--------------+------------+

In [7]:
%%sql
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'posts'
ORDER BY indexname;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

3 rows affected.

+----------------------+----------------------------------------------------------------------------+
|      indexname       |                                  indexdef                                  |
+----------------------+----------------------------------------------------------------------------+
| idx_posts_created_at | CREATE INDEX idx_posts_created_at ON public.posts USING btree (created_at) |
| idx_posts_fk_user_id | CREATE INDEX idx_posts_fk_user_id ON public.posts USING btree (fk_user_id) |
|      posts_pkey      |      CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (id)       |
+----------------------+----------------------------------------------------------------------------+

In [13]:
%%sql
SELECT
    indexrelname AS index_name,
    idx_scan AS times_used,
    pg_size_pretty(pg_relation_size(indexrelid)) AS index_size
FROM
    pg_stat_user_indexes
WHERE
    relname = 'posts'
ORDER BY
    idx_scan DESC;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

3 rows affected.

+----------------------+------------+------------+
|      index_name      | times_used | index_size |
+----------------------+------------+------------+
| idx_posts_created_at |     3      |   66 MB    |
|      posts_pkey      |     2      |   214 MB   |
| idx_posts_fk_user_id |     2      |   90 MB    |
+----------------------+------------+------------+

|                                                      |                                                              |
| ---------------------------------------------------- | ------------------------------------------------------------ |
| TOAST<br />The Oversized-Attribute Storage Technique | Is a mechanism that automatically compresses or moves large field values (such as long `text`, `jsonb`, or `bytea` data) to a separate, dedicated "TOAST table". It ensures rows fit within standard page sizes (8 KB), enhancing performance by allowing more rows to fit in memory |
|                                                      |                                                              |
|                                                      |                                                              |

In [15]:
%%sql
select * from comments

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

60000000 rows affected.

+----+------------+------------+-------------------+----------------------------------+
| id | fk_user_id | fk_post_id |      content      |            created_at            |
+----+------------+------------+-------------------+----------------------------------+
| 1  |   132467   |     1      | Comment on post 1 | 2026-02-21 01:52:36.451143+00:00 |
| 2  |   419411   |     1      | Comment on post 1 | 2026-02-21 01:52:36.451143+00:00 |
| 3  |   800173   |     1      | Comment on post 1 | 2026-02-21 01:52:36.451143+00:00 |
| 4  |   987223   |     1      | Comment on post 1 | 2026-02-21 01:52:36.451143+00:00 |
| 5  |   454458   |     1      | Comment on post 1 | 2026-02-21 01:52:36.451143+00:00 |
| 6  |   549600   |     1      | Comment on post 1 | 2026-02-21 01:52:36.451143+00:00 |
| 7  |   607979   |     2      | Comment on post 2 | 2026-02-21 01:52:36.451143+00:00 |
| 8  |   262990   |     2      | Comment on post 2 | 2026-02-21 01:52:36.451143+00:00 |
| 9  |   17513    |     2      | Comment on post 2 | 2026-02-21 01:52:36.451143+00:00 |
| 10 |   529873   |     2      | Comment on post 2 | 2026-02-21 01:52:36.451143+00:00 |
+----+------------+------------+-------------------+----------------------------------+
Truncated to displaylimit of 10.

In [8]:
import pandas as pd
from database_as_crime_scene.db.connection import get_engine
engine=get_engine()
df = pd.read_sql('select 1 +1', engine)
df.head()

   ?column?
0         2

In [9]:
%%sql
EXPLAIN (FORMAT JSON) select * from comments LIMIT 10;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

1 rows affected.

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                            QUERY PLAN                                                                                                                                                                                                           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [{'Plan': {'Node Type': 'Limit', 'Parallel Aware': False, 'Async Capable': False, 'Startup Cost': 0.0, 'Total Cost': 0.2, 'Plan Rows': 10, 'Plan Width': 55, 'Plans': [{'Node Type': 'Seq Scan', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Relation Name': 'comments', 'Alias': 'comments', 'Startup Cost': 0.0, 'Total Cost': 1218557.28, 'Plan Rows': 60000028, 'Plan Width': 55}]}}] |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [20]:
result = %sql EXPLAIN (FORMAT JSON) select * from comments LIMIT 10;
print(type(result))
df = result.DataFrame()
df.head()

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

1 rows affected.

<class 'sql.run.resultset.ResultSet'>

                                          QUERY PLAN
0  [{'Plan': {'Node Type': 'Limit', 'Parallel Awa...

In [11]:
%%sql
EXPLAIN comments;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

RuntimeError: If using snippets, you may pass the --with argument explicitly.
For more details please refer: https://jupysql.ploomber.io/en/latest/compose.html#with-argument


Original error message from DB driver:
(psycopg2.errors.SyntaxError) syntax error at or near "comments"
LINE 1: EXPLAIN comments;
                ^

[SQL: EXPLAIN comments;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [12]:
%%sql
SELECT MAX(pg_column_size(t.*)) as max_row_size,
       MIN(pg_column_size(t.*)) as min_row_size
FROM comments t;

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

1 rows affected.

+--------------+--------------+
| max_row_size | min_row_size |
+--------------+--------------+
|      88      |      77      |
+--------------+--------------+

# Troubleshooting
- sometimes base module doesnt load properly, use following to reload properly

In [8]:
%autoreload 2

In [9]:
%%sql
SELECT u.id, count(p.id) "post_count"
FROM users_profile u
RIGHT JOIN posts p ON u.id = p.fk_user_id
GROUP By u.id
HAVING u.id = 299093
ORDER BY count(p.id) ASC

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

1 rows affected.

+--------+------------+
|   id   | post_count |
+--------+------------+
| 299093 |     10     |
+--------+------------+

In [1]:
from database_as_crime_scene.db.connection import get_database_url
print(get_database_url())

postgresql://postgres:postgres@postgres:5432/mydb

In [2]:
from database_as_crime_scene.db.connection import get_query, get_execution_plan
from database_as_crime_scene.notebook import Notebook
from database_as_crime_scene.jupyter.mermaid import generate_mermaid_from_execution_plan, draw
from database_as_crime_scene.jupyter.mermaid_execution_plan import build_execution_tree,build_flamegraph

sql_query = """ 
SELECT u.id, count(p.id) "post_count"
FROM users_profile u
RIGHT JOIN posts p ON u.id = p.fk_user_id
GROUP By u.id

ORDER BY count(p.id) ASC
"""
##get_query("SELECT current_database(), current_schema();")
df = get_query(sql_query)
execution_plan = get_execution_plan(sql_query)
print(execution_plan)

n = Notebook()
Notebook.print_sql(sql_query)

df.head()

mm_temp = generate_mermaid_from_execution_plan(execution_plan)
draw(mm_temp)


tree = build_execution_tree(execution_plan[0]["Plan"])
flame = build_flamegraph(execution_plan[0]["Plan"])

draw(tree)
draw(flame)

[{'Plan': {'Node Type': 'Sort', 'Parallel Aware': False, 'Async Capable': False, 'Startup Cost': 1021883.54, 'Total Cost': 1024383.54, 'Plan Rows': 1000000, 'Plan Width': 16, 'Actual Startup Time': 3388.935, 'Actual Total Time': 3470.989, 'Actual Rows': 1000000, 'Actual Loops': 1, 'Output': ['u.id', '(count(p.id))'], 'Sort Key': ['(count(p.id))'], 'Sort Method': 'external merge', 'Sort Space Used': 25488, 'Sort Space Type': 'Disk', 'Shared Hit Blocks': 195, 'Shared Read Blocks': 122785, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 95326, 'Temp Written Blocks': 134122, 'Plans': [{'Node Type': 'Aggregate', 'Strategy': 'Hashed', 'Partial Mode': 'Finalize', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Startup Cost': 875603.94, 'Total Cost': 905135.19, 'Plan Rows': 1000000, 'Plan Width': 16, 'Actual Startup Time': 2854.605, 'Actual Total Time': 3285.18, 'Actual Rows': 1000000, 'Actual Loops': 1, 'Output': ['u.id', 'count(p.id)'], 'Group Key': ['u.id'], 'Planned Partitions': 16, 'HashAgg Batches': 81, 'Peak Memory Usage': 11153, 'Disk Usage': 47936, 'Shared Hit Blocks': 192, 'Shared Read Blocks': 122785, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 88959, 'Temp Written Blocks': 127740, 'Plans': [{'Node Type': 'Gather', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Startup Cost': 496792.96, 'Total Cost': 747478.94, 'Plan Rows': 2000000, 'Plan Width': 16, 'Actual Startup Time': 2151.676, 'Actual Total Time': 2573.317, 'Actual Rows': 1344377, 'Actual Loops': 1, 'Output': ['u.id', '(PARTIAL count(p.id))'], 'Workers Planned': 2, 'Workers Launched': 2, 'Single Copy': False, 'Shared Hit Blocks': 192, 'Shared Read Blocks': 122785, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 80749, 'Temp Written Blocks': 114793, 'Plans': [{'Node Type': 'Aggregate', 'Strategy': 'Hashed', 'Partial Mode': 'Partial', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Startup Cost': 495792.96, 'Total Cost': 546478.94, 'Plan Rows': 1000000, 'Plan Width': 16, 'Actual Startup Time': 2142.42, 'Actual Total Time': 2479.256, 'Actual Rows': 448126, 'Actual Loops': 3, 'Output': ['u.id', 'PARTIAL count(p.id)'], 'Group Key': ['u.id'], 'Planned Partitions': 16, 'HashAgg Batches': 17, 'Peak Memory Usage': 8337, 'Disk Usage': 96720, 'Shared Hit Blocks': 192, 'Shared Read Blocks': 122785, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 80749, 'Temp Written Blocks': 114793, 'Workers': [{'Worker Number': 0, 'Actual Startup Time': 2137.83, 'Actual Total Time': 2495.944, 'Actual Rows': 483397, 'Actual Loops': 1, 'HashAgg Batches': 17, 'Peak Memory Usage': 8337, 'Disk Usage': 96704, 'JIT': {'Functions': 17, 'Options': {'Inlining': True, 'Optimization': True, 'Expressions': True, 'Deforming': True}, 'Timing': {'Generation': 0.587, 'Inlining': 39.277, 'Optimization': 21.089, 'Emission': 25.074, 'Total': 86.027}}, 'Shared Hit Blocks': 68, 'Shared Read Blocks': 41116, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 26759, 'Temp Written Blocks': 38325}, {'Worker Number': 1, 'Actual Startup Time': 2137.952, 'Actual Total Time': 2480.119, 'Actual Rows': 486256, 'Actual Loops': 1, 'HashAgg Batches': 17, 'Peak Memory Usage': 8337, 'Disk Usage': 96832, 'JIT': {'Functions': 17, 'Options': {'Inlining': True, 'Optimization': True, 'Expressions': True, 'Deforming': True}, 'Timing': {'Generation': 0.6, 'Inlining': 40.387, 'Optimization': 21.093, 'Emission': 24.183, 'Total': 86.264}}, 'Shared Hit Blocks': 57, 'Shared Read Blocks': 40789, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 26999, 'Temp Written Blocks': 38326}], 'Plans': [{'Node Type': 'Hash Join', 'Parent Relationship': 'Outer', 'Parallel Aware': True, 'Async Capable': False, 'Join Type': 'Left', 'Startup Cost': 21303.0, 'Total Cost': 228892.89, 'Plan Rows': 4166245, 'Plan Width': 16, 'Actual Startup Time': 857.326, 'Actual Total Time': 1480.19, 'Actual Rows': 3333333, 'Actual Loops': 3, 'Output': ['u.id', 'p.id'], 'Inner Unique': True, 'Hash Cond': '(p.fk_user_id = u.id)', 'Shared Hit Blocks': 192, 'Shared Read Blocks': 122785, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 46970, 'Temp Written Blocks': 47056, 'Workers': [{'Worker Number': 0, 'Actual Startup Time': 856.794, 'Actual Total Time': 1477.098, 'Actual Rows': 3331705, 'Actual Loops': 1, 'Shared Hit Blocks': 68, 'Shared Read Blocks': 41116, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 15507, 'Temp Written Blocks': 15760}, {'Worker Number': 1, 'Actual Startup Time': 845.307, 'Actual Total Time': 1472.577, 'Actual Rows': 3358921, 'Actual Loops': 1, 'Shared Hit Blocks': 57, 'Shared Read Blocks': 40789, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 15627, 'Temp Written Blocks': 15632}], 'Plans': [{'Node Type': 'Seq Scan', 'Parent Relationship': 'Outer', 'Parallel Aware': True, 'Async Capable': False, 'Relation Name': 'posts', 'Schema': 'public', 'Alias': 'p', 'Startup Cost': 0.0, 'Total Cost': 154339.45, 'Plan Rows': 4166245, 'Plan Width': 16, 'Actual Startup Time': 0.046, 'Actual Total Time': 339.158, 'Actual Rows': 3333333, 'Actual Loops': 3, 'Output': ['p.id', 'p.fk_user_id'], 'Shared Hit Blocks': 96, 'Shared Read Blocks': 112581, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 0, 'Workers': [{'Worker Number': 0, 'Actual Startup Time': 0.04, 'Actual Total Time': 340.756, 'Actual Rows': 3351576, 'Actual Loops': 1, 'Shared Hit Blocks': 34, 'Shared Read Blocks': 37734, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 0}, {'Worker Number': 1, 'Actual Startup Time': 0.05, 'Actual Total Time': 342.367, 'Actual Rows': 3324244, 'Actual Loops': 1, 'Shared Hit Blocks': 26, 'Shared Read Blocks': 37425, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 0}]}, {'Node Type': 'Hash', 'Parent Relationship': 'Inner', 'Parallel Aware': True, 'Async Capable': False, 'Startup Cost': 14466.67, 'Total Cost': 14466.67, 'Plan Rows': 416667, 'Plan Width': 8, 'Actual Startup Time': 131.409, 'Actual Total Time': 131.41, 'Actual Rows': 333333, 'Actual Loops': 3, 'Output': ['u.id'], 'Hash Buckets': 262144, 'Original Hash Buckets': 262144, 'Hash Batches': 8, 'Original Hash Batches': 8, 'Peak Memory Usage': 7008, 'Shared Hit Blocks': 96, 'Shared Read Blocks': 10204, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 3052, 'Workers': [{'Worker Number': 0, 'Actual Startup Time': 127.009, 'Actual Total Time': 127.009, 'Actual Rows': 331592, 'Actual Loops': 1, 'Shared Hit Blocks': 34, 'Shared Read Blocks': 3382, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 1008}, {'Worker Number': 1, 'Actual Startup Time': 127.291, 'Actual Total Time': 127.292, 'Actual Rows': 329521, 'Actual Loops': 1, 'Shared Hit Blocks': 31, 'Shared Read Blocks': 3364, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 1008}], 'Plans': [{'Node Type': 'Seq Scan', 'Parent Relationship': 'Outer', 'Parallel Aware': True, 'Async Capable': False, 'Relation Name': 'users_profile', 'Schema': 'public', 'Alias': 'u', 'Startup Cost': 0.0, 'Total Cost': 14466.67, 'Plan Rows': 416667, 'Plan Width': 8, 'Actual Startup Time': 68.206, 'Actual Total Time': 93.248, 'Actual Rows': 333333, 'Actual Loops': 3, 'Output': ['u.id'], 'Shared Hit Blocks': 96, 'Shared Read Blocks': 10204, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 0, 'Workers': [{'Worker Number': 0, 'Actual Startup Time': 63.837, 'Actual Total Time': 88.763, 'Actual Rows': 331592, 'Actual Loops': 1, 'Shared Hit Blocks': 34, 'Shared Read Blocks': 3382, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 0}, {'Worker Number': 1, 'Actual Startup Time': 64.481, 'Actual Total Time': 89.185, 'Actual Rows': 329521, 'Actual Loops': 1, 'Shared Hit Blocks': 31, 'Shared Read Blocks': 3364, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 0}]}]}]}]}]}]}]}, 'Planning': {'Shared Hit Blocks': 188, 'Shared Read Blocks': 0, 'Shared Dirtied Blocks': 0, 'Shared Written Blocks': 0, 'Local Hit Blocks': 0, 'Local Read Blocks': 0, 'Local Dirtied Blocks': 0, 'Local Written Blocks': 0, 'Temp Read Blocks': 0, 'Temp Written Blocks': 0}, 'Planning Time': 0.551, 'Triggers': [], 'JIT': {'Functions': 58, 'Options': {'Inlining': True, 'Optimization': True, 'Expressions': True, 'Deforming': True}, 'Timing': {'Generation': 2.074, 'Inlining': 124.855, 'Optimization': 77.535, 'Emission': 89.964, 'Total': 294.428}}, 'Execution Time': 3522.477}]

  1
  2 SELECT u.id, count(p.id) "post_count"
  3 FROM users_profile u
  4 RIGHT JOIN posts p ON u.id = p.fk_user_id
  5 GROUP By u.id
  6
  7 ORDER BY count(p.id) ASC
  8

<IPython.core.display.Image object>

<IPython.core.display.Image object>

<IPython.core.display.Image object>

In [37]:
from database_as_crime_scene.jupyter.mermaid import generate_mermaid_from_execution_plan, draw
query = """
EXPLAIN (FORMAT JSON) select * from comments LIMIT 10;
"""
result = %sql EXPLAIN (ANALYZE, FORMAT JSON) select * from comments LIMIT 10;
df = result.DataFrame()

plan = df["QUERY PLAN"][0]

mm_temp = generate_mermaid_from_execution_plan(plan)
draw(mm_temp)

Running query in 'postgresql://postgres:***@postgres:5432/mydb'

1 rows affected.

In [3]:
draw(flame)

<IPython.core.display.Image object>

In [9]:
from rich.console import Console
from rich.syntax import Syntax
console = Console()
code = """
def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)

result = fibonacci(10)
print(f"Result: {result}")
"""
syntax = Syntax(
    code,
    "python",
    theme="ansi_light",
    line_numbers=True,
    highlight_lines={3, 5} # Optional: highlight specific line numbers
)
console.print(syntax)

inspect(syntax)

  1
  2 def fibonacci(n):
❱ 3     if n <= 1:
  4         return n
❱ 5     return fibonacci(n-1) + fibonacci(n-2)
  6
  7 result = fibonacci(10)
  8 print(f"Result: {result}")
  9

╭───────────────────────────────────────── <class 'rich.syntax.Syntax'> ──────────────────────────────────────────╮
│ Construct a Syntax object to render syntax highlighted code.                                                    │
│                                                                                                                 │
│ ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│ │ <rich.syntax.Syntax object at 0xffff8037ac10>                                                               │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                 │
│ background_color = None                                                                                         │
│ background_style = Style()                                                                                      │
│             code = '\ndef fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n-1) +          │
│                    fibonacci(n-2)\n\nresult = fibonacci(10)\nprint(f"Result: {result}")\n'                      │
│       code_width = None                                                                                         │
│           dedent = False                                                                                        │
│    default_lexer = <pygments.lexers.TextLexer with {'stripnl': False, 'ensurenl': True, 'tabsize': 4}>          │
│  highlight_lines = {3, 5}                                                                                       │
│    indent_guides = False                                                                                        │
│            lexer = <pygments.lexers.PythonLexer with {'stripnl': False, 'ensurenl': True, 'tabsize': 4}>        │
│     line_numbers = True                                                                                         │
│       line_range = None                                                                                         │
│          padding = (0, 0, 0, 0)                                                                                 │
│       start_line = 1                                                                                            │
│         tab_size = 4                                                                                            │
│        word_wrap = False                                                                                        │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [8]:
import pprint
data = [{'a': list(range(10)), 'b': {'c': [1, 2, 3], 'd': 'hello'}}] * 5
pprint.pprint(data, indent=4, width=80)

[   {'a': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'b': {'c': [1, 2, 3], 'd': 'hello'}},
    {'a': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'b': {'c': [1, 2, 3], 'd': 'hello'}},
    {'a': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'b': {'c': [1, 2, 3], 'd': 'hello'}},
    {'a': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'b': {'c': [1, 2, 3], 'd': 'hello'}},
    {'a': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 'b': {'c': [1, 2, 3], 'd': 'hello'}}]

In [9]:
import pandas as pd

# Create a sample DataFrame
df = pd.DataFrame({'A': range(10), 'B': [f'Item_{i}' for i in range(10)]})

# To show all rows and columns (overriding default limits)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Display the DataFrame
display(df)

   A       B
0  0  Item_0
1  1  Item_1
2  2  Item_2
3  3  Item_3
4  4  Item_4
5  5  Item_5
6  6  Item_6
7  7  Item_7
8  8  Item_8
9  9  Item_9

In [1]:
!python -m rich

                                 Rich features

    Colors    ✓ 4-bit color                 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
              ✓ 8-bit color                 ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
              ✓ Truecolor (16.7 million)    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
              ✓ Dumb terminals              ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
              ✓ Automatic color conversion  ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

    Styles    All ansi styles: bold, dim, italic, underline, strikethrough,
              reverse, and even blink.

     Text     Word wrap text. Justify left, center, right or full.

              Lorem ipsum       Lorem ipsum        Lorem ipsum Lorem      ipsum
              dolor sit amet, dolor sit amet,  dolor sit amet, dolor sit  amet,
              consectetur       consectetur        consectetur consectetur
              adipiscing        adipiscing    adipiscing elit. adipiscing elit.
              elit. Quisque    elit. Quisque  Quisque in metus Quisque in metus
              in metus sed     in metus sed         sed sapien sed       sapien
              sapien              sapien             ultricies ultricies
              ultricies          ultricies        pretium a at pretium   a   at
              pretium a at     pretium a at    justo. Maecenas justo.  Maecenas
              justo. Maecenas justo. Maecenas  luctus velit et luctus velit  et
              luctus velit et luctus velit et  auctor maximus. auctor maximus.
              auctor maximus. auctor maximus.

    Asian     🇨🇳  该库支持中文，日文和韩文文本！
   language   🇯🇵
   support    ライブラリは中国語、日本語、韓国語のテキストをサポートしています
              🇰🇷  이 라이브러리는 중국어, 일본어 및 한국어 텍스트를 지원합니다

    Markup    Rich supports a simple bbcode-like markup for color, style, and
              emoji! 👍 🍎 🐜 🐻 🥖 🚌

    Tables     Date           Title         Production Budget       Box Office
              ─────────────────────────────────────────────────────────────────
               Dec 20, 2019   Star Wars:         $275,000,000     $375,126,118
                              The Rise of
                              Skywalker
               May 25, 2018   Solo: A            $275,000,000     $393,151,347
                              Star Wars
                              Story
               Dec 15, 2017   Star Wars          $262,000,000   $1,332,539,889
                              Ep. VIII:
                              The Last
                              Jedi
               May 19, 1999   Star Wars          $115,000,000   $1,027,044,677
                              Ep. I: The
                              phantom
                              Menace

    Syntax       1 def iter_last(values: Itera  {
 highlighting    2 │   """Iterate and generate  │   'foo': [
      &          3 │   iter_values = iter(valu  │   │   3.1427,
    pretty       4 │   try:                     │   │   (
   printing      5 │   │   previous_value = ne  │   │   │   'Paul Atreides',
                 6 │   except StopIteration:    │   │   │   'Vladimir
                 7 │   │   return               Harkonnen',
                 8 │   for value in iter_value  │   │   │   'Thufir Hawat'
                 9 │   │   yield False, previo  │   │   )
                10 │   │   previous_value = va  │   ],
                11 │   yield True, previous_va  │   'atomic': (
                                                │   │   False,
                                                │   │   True,
                                                │   │   None
                                                │   )
                                                }

   Markdown   # Markdown                                   Markdown

              Supports much of the *markdown*   Supports much of the markdown
              __syntax__!                       syntax!

              - Headers                          • Headers
              - Basic formatting: **bold**,      • Basic formatting: bold,
              *italic*, `code`                     italic, code
              - Block quotes                     • Block quotes
              - Lists, and more...               • Lists, and more...


    +more!    Progress bars, columns, styled logging handler, tracebacks,
              etc...

rendered in 35.9ms (cold cache)
rendered in 13.7ms (warm cache)

╭─────────────────────── Help ensure Rich is maintained ───────────────────────╮
│                                                                              │
│  Hope you enjoy using Rich!                                                  │
│                                                                              │
│  Consider sponsoring to ensure this project is maintained.                   │
│                                                                              │
│  https://github.com/sponsors/willmcgugan                                     │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

In [2]:
from rich import print
print("[italic red]Hello[/italic red] World!", locals())

Hello World!
{
    '__name__': '__main__',
    '__doc__': 'Automatically created module for IPython interactive environment',
    '__package__': None,
    '__loader__': None,
    '__spec__': None,
    '__builtin__': <module 'builtins' (built-in)>,
    '__builtins__': <module 'builtins' (built-in)>,
    '_ih': [
        '',
        "get_ipython().system('python -m rich')",
        'from rich import print\nprint("[italic red]Hello[/italic red] World!", locals())'
    ],
    '_oh': {},
    '_dh': [PosixPath('/app/notebooks')],
    'In': [
        '',
        "get_ipython().system('python -m rich')",
        'from rich import print\nprint("[italic red]Hello[/italic red] World!", locals())'
    ],
    'Out': {},
    'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at
0xffff9005bc10>>,
    'exit': <IPython.core.autocall.ZMQExitAutocall object at 0xffff90074750>,
    'quit': <IPython.core.autocall.ZMQExitAutocall object at 0xffff90074750>,
    'open': <function open at 0xffff926f8e00>,
    '_': '',
    '__': '',
    '___': '',
    '__session__': '/app/notebooks/Untitled.ipynb',
    '_i': '!python -m rich',
    '_ii': '',
    '_iii': '',
    '_i1': '!python -m rich',
    '_exit_code': 0,
    '_i2': 'from rich import print\nprint("[italic red]Hello[/italic red] World!", locals())',
    'print': <function print at 0xffff900e8ae0>
}